beta/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

app_name = "beta"

urlpatterns = [
    path('', views.addName, name="beta-page"),
    path('delete/<int:id>', views.delete, name="delete"),
    path('display/', views.getDisplay, name="display-page")
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += staticfiles_urlpatterns()

formApp/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.get_name, name="form-pages"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += staticfiles_urlpatterns()

story4_web/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('work/', views.work, name="work"),
    path('', views.about),
    path('form/', include('formApp.urls')),
    path('beta/', include('beta.urls')),
    path('contact/', views.contact),
    path('soon/', views.soon),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += staticfiles_urlpatterns()

beta/models.py
from django.db import models

# Create your models here.
class BetaModel(models.Model):
    name = models.CharField(max_length=100, default="")
    location = models.CharField(max_length=100, default="")
    categories = models.CharField(max_length=100, default="")
    date = models.DateField(max_length=100, default="")

formApp/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
    name = models.CharField(max_length=100, default="")
    # location = models.CharField(max_length=100, default="")
    # categories = models.CharField(max_length=100, default="")
    # date = models.DateTimeField(max_length=100, auto_now_add=True)

class Assignment(models.Model):
    name = models.CharField(max_length=100, default="")
    location = models.CharField(max_length=100, default="")
    categories = models.CharField(max_length=100, default="")
    date = models.DateTimeField(max_length=100, auto_now_add=True)

beta/forms.py
from django import forms
from .models import BetaModel

class BetaForm(forms.Form):
    name = forms.CharField(required=True)
    location = forms.CharField(required=True)
    categories = forms.CharField(required=True)
    date = forms.DateField(required=True, widget=forms.DateInput(
        attrs={
            "class":"form-control",
            "type":"date",
        }
    ))
    # class Meta:
    #     model = BetaModel
    #     fields = "__all__"

formApp/forms.py
from django import forms
from . import models

class NameForm(forms.Form):
    name = forms.CharField(label="Name",required=True)
    location = forms.CharField(label="Location",required=False)
    categories = forms.CharField(label="Categories",required=False)
    class Meta:
        model = models.Assignment
        fields = ['name','location','categories']

beta/views.py
from django.shortcuts import render,redirect
from .models import BetaModel
from .forms import BetaForm
# Create your views here.
def addName(request):
    if request.method=="POST":
        form = BetaForm(request.POST)
        if form.is_valid():
            b = BetaModel(
                name = form.cleaned_data['name'],
                location = form.cleaned_data['location'],
                categories = form.cleaned_data['categories'],
                date = form.cleaned_data['date'],
                )
            b.save()

    form = BetaForm()
    return render(request, 'beta/betaPage.html', {'form':form})

def getDisplay(request):
    beta = BetaModel.objects.all().order_by("date")
    return render(request, 'beta/displayPage.html', {'beta':beta})

def delete(request, id):
    task = BetaModel.objects.get(pk=id)
    task.delete()
    return redirect("beta:display-page")

formApp/views.py
from django.shortcuts import render,redirect
from . import forms
from .models import Task,Assignment
# Create your views here.
def get_name(request):
    if(request.method == "POST"):  
        form = forms.NameForm(request.POST, request.FILES)
        if(form.is_valid()):
            a = Assignment(
                name = form.cleaned_data["name"],
                location = form.cleaned_data["location"],
                categories = form.cleaned_data["categories"],
            )
            a.save()
            return redirect("formApp:form_pages")
    else:
        form = forms.NameForm()

    assignment = Assignment.objects.all()    
    return render(request, 'form/formPage.html', {"assignment":assignment, "forms":form})
    # form = forms.NameForm()
    # return render(request, 'form/formPage.html', {'form':form})
    

story4_web/views.py
from django.http import HttpResponse
from django.shortcuts import render

def about(request):
    return(render(request,'about.html'))

def work(request):
    return(render(request,'work.html'))

def contact(request):
    return(render(request,'contact.html'))

def soon(request):
    return(render(request,'media.html'))

beta/templates/beta/betaPage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <style>
        #title{
            height: 20vh;
            padding-top: 5%;
            padding-bottom: 8%;
        }
        form{
            display: flex;
            justify-content: center;
        }
        .form-row{
            width: 70vw;
        }
        #submit-div{
            padding-top: 5%;
            display: flex;
            justify-content: center;
            align-content: center;
        }
    </style>
</head>
<body>
    <div id="title" class="text-center">
        <h1>Add Your Task.</h1>
    </div>
    <form action="{% url 'beta:beta-page' %}" method="POST" class="text-center">
        {% csrf_token %}
        <div class="form-row align-items-center">
            <div class="col-sm-3 my-1">
                <label class="sr-only" for="inlineFormInputGroupUsername">Task</label>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <div class="input-group-text">Task</div>
                    </div>
                    {{ form.name }}
                </div>
            </div>
            <div class="col-sm-3 my-1">
                <label class="sr-only" for="inlineFormInputGroupUsername">Location</label>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <div class="input-group-text">Location</div>
                    </div>
                    {{ form.location }}
                </div>
            </div>
            <div class="col-sm-3 my-1">
                <label class="sr-only" for="inlineFormInputGroupUsername">Categories</label>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <div class="input-group-text">Categories</div>
                    </div>
                    {{ form.categories }}
                </div>
            </div>
            <div class="col-sm-3 my-1">
                <label class="sr-only" for="inlineFormInputGroupUsername">Date</label>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <div class="input-group-text">Date</div>
                    </div>
                    {{ form.date }}
                </div>
            </div>
            <div class="col-12 my-1" id="submit-div">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
            <a class="col-12 my-4" href="/beta/display">See my schedule</a>
        </div>
    </form>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script> 
</body>
</html>

beta/templates/beta/displayPage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    <div class="container-fluid" style="width:50vh;">
        {% for b in beta %}
        <form action='{% url "beta:delete" b.id %}' method="POST">
            {% csrf_token %}
            <div class="card text-white bg-dark my-5" style="border-radius: 2%;">
                <div class="card-header" style="color:yellow;margin-top:1%;"><h4>{{ b.name }}</h4></div>
                <div class="card-body">
                    <p class="card-text">Location: {{ b.location }}</p>
                    <p class="card-text">Categories: {{ b.categories }}</p>
                    <p class="card-text">Due Date: {{ b.date }}</p>
                    <button type="submit" style="float: right;" class="btn btn-warning">Delete</button>
                </div>
            </div>
        </form>
        {% endfor %}
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script> 
</body>
</html>

formApp/templates/form/formPage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>form</title>
</head>
<body>
    <form action="{% url 'form-pages' %}"" method="POST">
        {% csrf_token %}
        <!-- <label for="name_form">Name : </label>
        <input type="text" id="name_form" name="name_form" value="{{ current_name }}"> -->
        {{ form }}
        <input type="submit" value="Submit">
    </form>
</body>
</html>

templates/about.html
{% extends 'navbar_layout.html' %}
{% load static %}

{% block content %}
    <div class="container-lg text-center landing" id="welcome">
        <img src="{% static 'avi.png' %}" class="img-fluid image-me" alt="avi">
        <h1>Hi, I'm Avi.</h1>
        <div id="bio">
            <p>An undergraduate of Informatic System, Universitas Indonesia, who love to design web and make an illustration.</p>
        </div>
    </div>
    <div class="container-lg text-center" id="hobbies">
        <h1>What I Love.</h1>
        <div class="container hobby">
            <img class="img-fluid hobby-photo" src="{% static 'koding.jpg' %}" alt="coding">
            <div class="container">
                <h2>Coding.</h2>
                <p>Currently, I code using python, java, and JS. I also assigned as programming class lecturer assistant.</p>
            </div>
        </div>
        <div class="container hobby" id="design">
            <img class="img-fluid hobby-photo" src="{% static 'webing.png' %}" alt="webing">
            <div class="container">
                <h2>Designing.</h2>
                <p>I love to design and making illustration. I prefer simple and minimal style.</p>
            </div>
        </div>
        <div class="container hobby">
            <img class="img-fluid hobby-photo" src="{% static 'reading.png' %}" alt="reading">
            <div class="container">
                <h2>Reading.</h2>
                <p>Most of the time, I read novel and science book. Currently I’m reading Cosmos by Carl Sagan.</p>
            </div>
        </div>
    </div>
    <footer class="text-center">
        <p>2019 Ardiaf Rizky</p>
    </footer>
{% endblock %}

templates/contact.html
{% extends 'navbar_layout.html' %}
{% load static %}

{% block content %}
    <div class="container-lg text-center landing" id="welcome">
        <img src="{% static 'contact1.png' %}" class="img-fluid img-contact" alt="avi">
        <h1>Get In Touch.</h1>
        <div id="bio">
            <p>You are only one click away from me.</p>
        </div>
        <div class="div-button text-center">
        <button type="button" class="btn btn-outline-success">Message Me</button>
        </div>
    </div>
{% endblock %}

templates/media.html
{% extends 'navbar_layout.html' %}

{% block content %}
    <div class="container-lg text-center landing cons-2" id="welcome">
        <img src="/assets/line2.png" class="img-fluid img-contact" alt="avi">
        <h1>Coming Soon.</h1>
        <div id="bio">
            <p>This page is under construction.</p>
        </div>
        <div class="div-button text-center">
        <a role="button" class="btn btn-outline-warning" href="about.html">Back to Home</a>
        </div>
    </div>
{% endblock %}

templates/navbar_layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>Document</title>
</head>
<body>
    <ul class="nav justify-content-center" {% if  'work' in request.get_full_path %}style="background-color:#1f1d1d ;"{% endif %}>
        <li class="nav-item">
            <a class="nav-link" {% if  'work' in request.get_full_path %}style="color:#D8E359;"{% endif %} href="/">About</a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" {% if  'work' in request.get_full_path %}style="color:#D8E359;"{% endif %} href="{% url 'work' %}">Work</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" {% if  'work' in request.get_full_path %}style="color:#D8E359;"{% endif %} href="/contact">Contact</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" {% if  'work' in request.get_full_path %}style="color:#D8E359;"{% endif %} href="/beta">Schedule</a>
        </li>
    </ul>
    {% block content %}
    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script> 
</body>
</html>

templates/work.html
{% extends 'navbar_layout.html' %}
{% load static %}
{% block content %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <div class="container-lg text-center landing" id="work-landing">
        <img src="{% static 'avi.png' %}" class="img-fluid image-me" style="border: 5px solid rgb(122, 122, 122)" alt="avi">
        <h1>What I've been up to.</h1>
        <div id="bio">
            <p>Here’s some of my work and experience.</p>
        </div>
    </div>
    <div class="container-lg text-center landing" id="work-1">
        <img src="{% static 'Biro-Bisnis-dan-Kemitraan.png' %}" class="img-fluid img-work" alt="avi">
        <h1>BEM Fasilkom UI.</h1>
        <div id="bio">
            <p>Person in Charge of Partnership Division. Maintain relation with BEM Fasilkom’s website hosting provider. Making contract with sponsorship company, etc.</p>
        </div>
        <div class="div-button text-center">
            <a role="button" href="https://bem.cs.ui.ac.id/" class="btn btn-outline-primary">Visit</a>
       </div>
    </div>
    <div class="container-lg text-center landing" id="work-2">
        <img src="{% static 'java2.png' %}" class="img-fluid img-work" alt="avi">
        <h1>Lecturer Assistant.</h1>
        <div id="bio">
            <p>Lecturer Assistant of Programming Foundation class with Java language. Making lab assignment and project task. Teaching and giving feedback to student.</p>
        </div>
        <div class="div-button text-center">
            <a role="button" class="btn btn-outline-primary" href="http://siasisten.cs.ui.ac.id">Visit</a>
        </div>
    </div>
{% endblock %}